name: Generate 3D Profile

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate 3D profile contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: nazaraskroglu
          theme: night-rainbow
      - name: Push the 3D profile
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-three-d
          build_dir: ./profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
