name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # her 12 saatte bir çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: nazaraskroglu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push the snake files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
